import React, { useState } from 'react'

export default function App() {
  const [count, setCount] = useState(0)

  return (
    <main className="app">
      <h1>{{name}}</h1>
      <p>A minimal React + Vite app generated by Animica Studio Qt.</p>
      <button onClick={() => setCount((c) => c + 1)}>
        Count is {count}
      </button>
    </main>
  )
}
