// {{name}} — Animica pool miner dashboard.
// Polls the public pool mining status endpoint and renders headline stats.
// Generated by Animica Studio Qt (miner_dashboard template).

const STATUS_URL = 'https://pool.animica.org/api/mining/status'
const REFRESH_MS = 15000

function text(id, value) {
  const el = document.getElementById(id)
  if (el) el.textContent = value
}

function fmtHashrate(h) {
  const n = Number(h) || 0
  const units = ['H/s', 'KH/s', 'MH/s', 'GH/s', 'TH/s']
  let i = 0
  let v = n
  while (v >= 1000 && i < units.length - 1) {
    v /= 1000
    i += 1
  }
  return v.toFixed(2) + ' ' + units[i]
}

async function refresh() {
  const status = document.getElementById('status')
  try {
    const resp = await fetch(STATUS_URL, { headers: { Accept: 'application/json' } })
    if (!resp.ok) throw new Error('HTTP ' + resp.status)
    const data = await resp.json()

    text('hashrate', fmtHashrate(data.hashrate ?? data.network_hashrate))
    text('miners', String(data.miners ?? data.active_miners ?? '—'))
    text('height', String(data.height ?? data.pool_height ?? '—'))
    text('block', String(data.last_block ?? data.lastBlock ?? '—'))

    if (status) status.textContent = 'Updated ' + new Date().toLocaleTimeString()
  } catch (err) {
    if (status) status.textContent = 'Could not load pool status: ' + err.message
  }
}

refresh()
setInterval(refresh, REFRESH_MS)
