apiVersion: v1
kind: Namespace
metadata:
  name: cex-prod
  labels:
    name: cex-prod
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: cex-dev
  labels:
    name: cex-dev
    environment: development
