"""{{name}} — a tiny Animica inference agent.

Talks to any OpenAI-compatible endpoint (Animica pool, a local server, etc.)
via ``/chat/completions``. Generated by Animica Studio Qt (animica_agent template).

Configure with environment variables:

    ANIMICA_ENDPOINT   default https://pool.animica.org/v1
    ANIMICA_API_KEY    optional bearer token
    ANIMICA_MODEL      default anm-fast-8b

Run with:
    python agent.py "Explain what Animica is in one sentence."
"""
from __future__ import annotations

import os
import sys

import httpx

DEFAULT_ENDPOINT = "https://pool.animica.org/v1"
DEFAULT_MODEL = "anm-fast-8b"
SYSTEM_PROMPT = (
    "You are a concise, helpful assistant running on the Animica network."
)


def _endpoint() -> str:
    return os.environ.get("ANIMICA_ENDPOINT", DEFAULT_ENDPOINT).rstrip("/")


def _headers() -> dict[str, str]:
    headers = {"Content-Type": "application/json"}
    api_key = os.environ.get("ANIMICA_API_KEY", "").strip()
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    return headers


def ask(prompt: str, *, model: str | None = None, timeout: float = 120.0) -> str:
    """Send a single user prompt and return the assistant's reply text."""
    payload = {
        "model": model or os.environ.get("ANIMICA_MODEL", DEFAULT_MODEL),
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.3,
    }
    url = f"{_endpoint()}/chat/completions"
    resp = httpx.post(url, json=payload, headers=_headers(), timeout=timeout)
    resp.raise_for_status()
    data = resp.json()
    return data["choices"][0]["message"]["content"]


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    prompt = " ".join(args).strip() or "Say hello from the Animica network."
    try:
        print(ask(prompt))
    except httpx.HTTPError as exc:
        print(f"Request failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
