// {{name}} — a minimal Express.js HTTP API.
// Generated by Animica Studio Qt (node_express template).
//
// Run with:  npm install && npm start

const express = require('express')

const app = express()
app.use(express.json())

app.get('/health', (req, res) => {
  res.json({ status: 'ok' })
})

app.get('/', (req, res) => {
  res.json({ app: '{{name}}' })
})

app.post('/echo', (req, res) => {
  const message = (req.body && req.body.message) || ''
  res.json({ echo: message, length: String(message).length })
})

const port = process.env.PORT || 3000
app.listen(port, () => {
  console.log(`{{name}} listening on http://localhost:${port}`)
})

module.exports = app
