/**
 * Animica Explorer — Bootstrap cache loader
 * -----------------------------------------------------------------------------
 * Loads a precomputed bootstrap payload (generated by a CLI script) and seeds
 * IndexedDB so the explorer has data immediately on first load.
 */

import { getCache, isCacheAccessError, isCacheAvailable } from './cache';

type BootstrapPayload = {
  generatedAt?: string;
  chainId?: string | number;
  head?: any;
  blocks?: any[];
  txs?: any[];
};

function extractTxsFromBlocks(blocks: any[]): any[] {
  const out: any[] = [];
  for (const block of blocks) {
    const txs = block?.txs ?? block?.transactions ?? [];
    if (!Array.isArray(txs)) continue;
    for (const tx of txs) {
      if (tx && typeof tx === 'object' && (tx.hash || tx.txHash)) {
        out.push(tx);
      }
    }
  }
  return out;
}

function normalizeBlockHeight(block: any): number | null {
  const height = block?.height ?? block?.number ?? block?.header?.height;
  if (typeof height === 'number' && Number.isFinite(height)) return height;
  const parsed = Number(height);
  return Number.isFinite(parsed) ? parsed : null;
}

function normalizeBlockHash(block: any): string {
  return block?.hash ?? block?.blockHash ?? '';
}

function normalizeTxHash(tx: any): string | null {
  const hash = tx?.hash ?? tx?.txHash;
  return typeof hash === 'string' && hash.length > 0 ? hash : null;
}

export async function seedCacheFromBootstrap(opts?: {
  url?: string;
  force?: boolean;
}): Promise<void> {
  if (!isCacheAvailable() || typeof window === 'undefined') return;

  const url = opts?.url ?? '/bootstrap/chain.json';
  const chunkSize = 250;

  try {
    const cache = await getCache();
    if (!opts?.force) {
      const stats = await cache.getStats();
      if (stats.blocksCount > 0 || stats.txsCount > 0) {
        return;
      }
    }

    const response = await fetch(url, { cache: 'no-store' });
    if (!response.ok) {
      return;
    }

    const payload = (await response.json()) as BootstrapPayload;
    const blocks = Array.isArray(payload.blocks) ? payload.blocks : [];
    const txs = Array.isArray(payload.txs) ? payload.txs : extractTxsFromBlocks(blocks);

    if (blocks.length > 0) {
      const entries = blocks
        .map((block) => {
          const height = normalizeBlockHeight(block);
          if (height === null) return null;
          return {
            height,
            hash: normalizeBlockHash(block),
            data: block,
          };
        })
        .filter(Boolean) as Array<{ height: number; hash: string; data: any }>;

      const seenHeights = new Set<number>();
      const deduped = entries.filter((entry) => {
        if (seenHeights.has(entry.height)) return false;
        seenHeights.add(entry.height);
        return true;
      });

      for (let i = 0; i < deduped.length; i += chunkSize) {
        const chunk = deduped.slice(i, i + chunkSize);
        try {
          await cache.putBlocks(chunk);
        } catch (err) {
          console.debug('[bootstrap] Skipped bootstrap block chunk due to cache error:', err);
        }
      }
    }

    if (txs.length > 0) {
      for (const tx of txs) {
        const hash = normalizeTxHash(tx);
        if (!hash) continue;
        const blockHeight = tx.blockNumber ?? tx.height ?? tx.blockHeight;
        try {
          await cache.putTx(hash, tx, typeof blockHeight === 'number' ? blockHeight : undefined);
        } catch (err) {
          console.debug('[bootstrap] Skipped bootstrap tx due to cache error:', err);
        }
      }
    }

    if (blocks.length > 0) {
      const heights = blocks
        .map((block) => normalizeBlockHeight(block))
        .filter((height): height is number => height !== null);
      const maxHeight = heights.length > 0 ? Math.max(...heights) : null;
      if (maxHeight != null) {
        await cache.setLastSyncHeight(maxHeight);
      }
      await cache.setLastSyncTime(Date.now());
    }
  } catch (err) {
    if (isCacheAccessError(err)) {
      console.debug('[bootstrap] Explorer cache unavailable:', err);
    } else {
      console.warn('[bootstrap] Failed to seed explorer cache:', err);
    }
  }
}
