"""{{name}} — a minimal PySide6 desktop window.

Generated by Animica Studio Qt (qt_app template).

Run with:  python main.py
"""
from __future__ import annotations

import sys

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QApplication,
    QLabel,
    QPushButton,
    QVBoxLayout,
    QWidget,
)


class MainWindow(QWidget):
    """A simple window with a label and a button."""

    def __init__(self) -> None:
        super().__init__()
        self.setWindowTitle("{{name}}")
        self.resize(420, 220)

        self._clicks = 0
        self._label = QLabel("Hello from {{name}}!")
        self._label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        button = QPushButton("Click me")
        button.clicked.connect(self._on_click)

        layout = QVBoxLayout(self)
        layout.addWidget(self._label)
        layout.addWidget(button)

    def _on_click(self) -> None:
        self._clicks += 1
        self._label.setText(f"Clicked {self._clicks} time(s)")


def main() -> int:
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    return app.exec()


if __name__ == "__main__":
    sys.exit(main())
