server {
  listen 4321;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /app {
    return 302 https://aicf.animica.org;
  }

  location ~ ^/app/(.*)$ {
    return 302 https://aicf.animica.org/$1$is_args$args;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript image/svg+xml;
}
