import { NextRequest, NextResponse } from 'next/server';
import { publicOk, publicPreflight, PUBLIC_CORS } from '@/lib/api';
import { rateLimit } from '@/lib/apikey';
import { prisma } from '@/lib/db';
import { sweep, MEDIA_UPLOAD_TTL_SECS } from '@/lib/mediaQueue';
import { streamToFile, uploadPath, removeFile, freeDiskBytes, StreamTooLargeError } from '@/lib/mediaStore';
import { randomBytes } from 'node:crypto';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// 9.0.0 GPU Studios: large-input upload (video / audio / .blend / mastering reference).
// RAW BINARY body streamed straight to the gateway disk — never JSON, never base64, never
// a DB row's worth of bytes. Public keyless like the job submit (the id is the secret);
// nginx grants this route a bigger client_max_body_size than the rest of /api/mkt/.

const PURPOSES: Record<string, number> = {
  video: 512 * 1024 * 1024,
  blend: 512 * 1024 * 1024,
  audio: 200 * 1024 * 1024,
  reference: 200 * 1024 * 1024,
};

function clientIp(req: NextRequest): string {
  const xff = req.headers.get('x-forwarded-for');
  if (xff) return xff.split(',')[0].trim();
  return req.headers.get('x-real-ip') || 'unknown';
}

export function OPTIONS() {
  return publicPreflight();
}

export async function POST(req: NextRequest) {
  const ip = clientIp(req);
  const rl = rateLimit('mediaupload:' + ip, Number(process.env.MEDIA_UPLOADS_PER_MIN ?? 8));
  if (!rl.ok) {
    return NextResponse.json(
      { error: { code: 'rate_limited', message: `Too many uploads — retry in ${rl.retryAfter}s.` } },
      { status: 429, headers: { ...PUBLIC_CORS, 'retry-after': String(rl.retryAfter) } },
    );
  }
  await sweep();

  const purpose = (req.headers.get('x-anm-purpose') || '').trim().toLowerCase();
  const maxBytes = PURPOSES[purpose];
  if (!maxBytes) {
    return NextResponse.json(
      { error: { code: 'bad_purpose', message: `x-anm-purpose must be one of ${Object.keys(PURPOSES).join(', ')}.` } },
      { status: 400, headers: PUBLIC_CORS },
    );
  }
  // Global disk budget: keep a hard floor of free space (node DB + services share this
  // disk). Anonymous upload pressure must degrade honestly, not fill the disk.
  const RESERVE = Number(process.env.MEDIA_STORE_MIN_FREE_BYTES ?? 20 * 1024 * 1024 * 1024);
  if ((await freeDiskBytes()) < RESERVE + maxBytes) {
    return NextResponse.json(
      { error: { code: 'storage_full', message: 'Gateway storage is momentarily full — try again soon.' } },
      { status: 507, headers: PUBLIC_CORS },
    );
  }

  const mime = (req.headers.get('content-type') || 'application/octet-stream').split(';')[0].trim().slice(0, 100);

  // cuid-shaped id is generated by us; the path never contains client input.
  const id = 'mu' + randomBytes(14).toString('base64url').replace(/[^a-zA-Z0-9]/g, '').slice(0, 20) + Date.now().toString(36);
  const dest = uploadPath(id);
  let stored: { bytes: number; sha3: string };
  try {
    stored = await streamToFile(req.body, dest, maxBytes);
  } catch (e) {
    if (e instanceof StreamTooLargeError) {
      return NextResponse.json(
        { error: { code: 'too_large', message: `Max ${Math.round(maxBytes / 1048576)} MB for a ${purpose} upload.` } },
        { status: 413, headers: PUBLIC_CORS },
      );
    }
    return NextResponse.json({ error: { code: 'upload_failed', message: 'Upload stream failed — try again.' } }, { status: 400, headers: PUBLIC_CORS });
  }

  try {
    await prisma.mediaUpload.create({
      data: {
        id, purpose, mime,
        bytes: BigInt(stored.bytes),
        sha3: stored.sha3,
        path: dest,
        requesterIp: ip,
        expiresAt: new Date(Date.now() + MEDIA_UPLOAD_TTL_SECS * 1000),
      },
    });
  } catch (e) {
    await removeFile(dest);
    throw e;
  }

  return publicOk({
    upload_id: id,
    purpose,
    bytes: stored.bytes,
    sha3: stored.sha3,
    expires_in_secs: MEDIA_UPLOAD_TTL_SECS,
  }, { status: 201 });
}
