"""{{name}} — a minimal FastAPI service.

Generated by Animica Studio Qt (fastapi template).

Run with:
    uvicorn app.main:app --reload
or:
    python -m app.main
"""
from __future__ import annotations

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(
    title="{{name}}",
    description="A starter FastAPI service generated by Animica Studio Qt.",
    version="0.1.0",
)


class EchoRequest(BaseModel):
    """Request body for the echo endpoint."""

    message: str


class EchoResponse(BaseModel):
    """Response body for the echo endpoint."""

    echo: str
    length: int


@app.get("/health")
def health() -> dict[str, str]:
    """Liveness probe."""
    return {"status": "ok"}


@app.get("/")
def index() -> dict[str, str]:
    """Service root."""
    return {"app": "{{name}}", "docs": "/docs"}


@app.post("/echo", response_model=EchoResponse)
def echo(req: EchoRequest) -> EchoResponse:
    """Echo back the supplied message."""
    return EchoResponse(echo=req.message, length=len(req.message))


def main() -> None:
    import uvicorn

    uvicorn.run("app.main:app", host="127.0.0.1", port=8000, reload=False)


if __name__ == "__main__":
    main()
