apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-tls
  namespace: cex-prod
spec:
  secretName: api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - api.animica.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-tls
  namespace: cex-prod
spec:
  secretName: admin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - admin.animica.io
