// {{name}} — static site behaviour.
// Generated by Animica Studio Qt (static_site template).

(function () {
  'use strict'

  const button = document.getElementById('cta')
  const output = document.getElementById('output')
  let count = 0

  if (button && output) {
    button.addEventListener('click', function () {
      count += 1
      output.textContent = 'Hello from {{name}}! (' + count + ')'
    })
  }
})()
