"""{{PROJECT_NAME}} — generated by Animica Studio Template ({{DATE}})."""

# Author: {{AUTHOR}}

def main() -> None:
    print("Hello from Animica deterministic VM!")
    for i in range(3):
        print(f"tick={i}")
    # CURSOR


if __name__ == "__main__":
    main()
