"""{{name}} — a minimal command-line application.

Generated by Animica Studio Qt (python_cli template).
Run with:  python main.py --name Animica
"""
from __future__ import annotations

import argparse
import sys

APP_NAME = "{{name}}"


def greet(name: str) -> str:
    """Return a friendly greeting for ``name``."""
    return f"Hello, {name}! Welcome to {APP_NAME}."


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="{{slug}}",
        description="{{name}} — a starter Python CLI.",
    )
    parser.add_argument(
        "--name",
        default="world",
        help="name to greet (default: world)",
    )
    parser.add_argument(
        "--shout",
        action="store_true",
        help="print the greeting in upper case",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    message = greet(args.name)
    if args.shout:
        message = message.upper()
    print(message)
    return 0


if __name__ == "__main__":
    sys.exit(main())
