"""{{name}} — a minimal Animica wallet / payment stub.

A read-only, local-only demonstration of an Animica wallet model. It does NOT
hold private keys, sign transactions, or talk to a network — it is a safe
starting point you can extend. Generated by Animica Studio Qt (wallet_app template).

Run with:  python wallet.py
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from decimal import Decimal
from pathlib import Path

# Canonical Animica address format is bech32m: anim1...
EXAMPLE_ADDRESS = "anim1qexampleaddressreplacewithyourown000000000000"
STATE_FILE = Path("wallet_state.json")


@dataclass
class Transaction:
    """A single (simulated) ledger entry."""

    counterparty: str
    amount: Decimal
    memo: str = ""

    def to_dict(self) -> dict[str, str]:
        return {
            "counterparty": self.counterparty,
            "amount": str(self.amount),
            "memo": self.memo,
        }


@dataclass
class Wallet:
    """An in-memory, read-only wallet model."""

    address: str = EXAMPLE_ADDRESS
    balance: Decimal = Decimal("0")
    history: list[Transaction] = field(default_factory=list)

    def credit(self, amount: Decimal, counterparty: str, memo: str = "") -> None:
        """Record an incoming (simulated) payment."""
        if amount <= 0:
            raise ValueError("amount must be positive")
        self.balance += amount
        self.history.append(Transaction(counterparty, amount, memo))

    def to_dict(self) -> dict[str, object]:
        return {
            "address": self.address,
            "balance": str(self.balance),
            "history": [tx.to_dict() for tx in self.history],
        }

    def save(self, path: Path = STATE_FILE) -> None:
        path.write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")


def main() -> int:
    wallet = Wallet()
    # Demonstrate a couple of simulated credits.
    wallet.credit(Decimal("12.5"), "anim1qpoolpayout00000000000000000000000000000000", "pool payout")
    wallet.credit(Decimal("3.0"), "anim1qfriendaddress0000000000000000000000000000000", "gift")

    print(f"Address: {wallet.address}")
    print(f"Balance: {wallet.balance} ANM")
    print("History:")
    for tx in wallet.history:
        print(f"  +{tx.amount} ANM from {tx.counterparty}  ({tx.memo})")

    wallet.save()
    print(f"\nState written to {STATE_FILE}")
    print("Note: this is a read-only stub. It never holds keys or signs transactions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
