// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

/// Generated by animica-agent.
/// Replace this with your real contract implementation.
contract __NAME__ {
    address public owner;
    bytes public state;

    event Updated(address indexed sender, bytes value);

    constructor() {
        owner = msg.sender;
    }

    function set(bytes calldata value) external {
        require(msg.sender == owner, "not owner");
        state = value;
        emit Updated(msg.sender, value);
    }

    function get() external view returns (bytes memory) {
        return state;
    }
}
