# -*- mode: python ; coding: utf-8 -*-
#
# Unified, cross-platform PyInstaller spec for Animica Internet — the
# standalone .anm-only desktop browser (PySide6 + QtWebEngine).
#
# This single spec is consumed by all three per-OS build scripts:
#   - build_linux.sh        (onedir -> AppImage + tar.gz on Linux)
#   - build_macos.sh        (onedir -> .app BUNDLE -> .dmg/.zip on macOS)
#   - build_windows.ps1     (onedir -> Inno Setup installer on Windows)
#
# It produces a *windowed* (no-console) GUI application named "AnimicaInternet".
# On macOS it additionally emits an "AnimicaInternet.app" bundle via BUNDLE().
#
# CRITICAL — QtWebEngine: unlike the miner GUI, this app embeds Chromium.
# The frozen bundle MUST contain PySide6.QtWebEngineCore's data + binaries,
# including the QtWebEngineProcess helper executable, the Qt/resources/*.pak
# files and the qtwebengine_locales translations. We use collect_all("PySide6")
# (belt) on top of PyInstaller's own QtWebEngineCore hooks triggered by the
# hiddenimports (suspenders), plus a runtime hook that repairs plugin/helper
# paths at startup.
#
# PyInstaller does NOT guarantee that __file__ is defined inside a spec's exec
# namespace, so we locate the spec directory defensively and allow the build
# scripts to override paths through environment variables:
#
#   ANIMICA_INTERNET_SPEC_DIR   - directory containing this spec (packaging/)
#   ANIMICA_INTERNET_APP_DIR    - apps/animica-internet
#   ANIMICA_INTERNET_REPO_ROOT  - repository root
#   ANIMICA_INTERNET_ENTRY      - entry script (defaults to a generated launcher)
#   ANIMICA_INTERNET_NAME       - output name (defaults to "AnimicaInternet")
#   ANIMICA_INTERNET_UPX        - "1"/"0" toggle for UPX (default off; NEVER
#                                 safe on Qt/Chromium binaries)
#   ANIMICA_INTERNET_VERSION    - version string used for the macOS Info.plist
#
import os
import sys
from pathlib import Path


def _resolve_spec_dir() -> Path:
    # 1. Explicit override from the build script.
    env_dir = os.environ.get("ANIMICA_INTERNET_SPEC_DIR")
    if env_dir:
        return Path(env_dir).resolve()
    # 2. __file__ if PyInstaller happened to provide it.
    try:
        return Path(__file__).resolve().parent  # type: ignore[name-defined]
    except NameError:
        pass
    # 3. PyInstaller exposes the spec path via sys.argv on most versions.
    for arg in sys.argv:
        if arg.endswith(".spec"):
            return Path(arg).resolve().parent
    # 4. Last resort: current working directory.
    return Path(os.getcwd()).resolve()


SPEC_DIR = _resolve_spec_dir()
APP_DIR = Path(
    os.environ.get("ANIMICA_INTERNET_APP_DIR", str(SPEC_DIR.parent))
).resolve()
REPO_ROOT = Path(
    os.environ.get("ANIMICA_INTERNET_REPO_ROOT", str(APP_DIR.parent.parent))
).resolve()

APP_NAME = os.environ.get("ANIMICA_INTERNET_NAME", "AnimicaInternet")
APP_VERSION = os.environ.get("ANIMICA_INTERNET_VERSION", "0.1.0")
USE_UPX = os.environ.get("ANIMICA_INTERNET_UPX", "0") == "1"

IS_MACOS = sys.platform == "darwin"
IS_WINDOWS = sys.platform.startswith("win")

# ---------------------------------------------------------------------------
# Entry script. animica_internet/main.py uses *relative* imports, so it cannot
# be handed to PyInstaller directly as a script (no package context). We
# generate a tiny absolute-import launcher instead, unless the build script
# supplies one explicitly.
# ---------------------------------------------------------------------------
entry_env = os.environ.get("ANIMICA_INTERNET_ENTRY", "")
if entry_env and Path(entry_env).exists():
    ENTRY = Path(entry_env).resolve()
else:
    launcher_dir = APP_DIR / "build"
    launcher_dir.mkdir(parents=True, exist_ok=True)
    ENTRY = launcher_dir / "animica_internet_launcher.py"
    ENTRY.write_text(
        "# Auto-generated by animica-internet.spec — do not edit.\n"
        "import sys\n"
        "\n"
        "from animica_internet.main import main\n"
        "\n"
        "if __name__ == '__main__':\n"
        "    sys.exit(main())\n",
        encoding="utf-8",
    )

print(f"[spec] APP_NAME   = {APP_NAME}")
print(f"[spec] APP_DIR    = {APP_DIR}")
print(f"[spec] REPO_ROOT  = {REPO_ROOT}")
print(f"[spec] ENTRY      = {ENTRY}")
print(f"[spec] platform   = {sys.platform}  upx={USE_UPX}")

if not ENTRY.exists():
    raise SystemExit(f"[spec] entry script not found: {ENTRY}")

block_cipher = None

# ---------------------------------------------------------------------------
# Collect ALL of PySide6: data files (Qt/resources/*.pak, translations incl.
# qtwebengine_locales, qml, ...), binaries (Qt libs, plugins, the
# QtWebEngineProcess helper) and every importable submodule. QtWebEngine does
# not work with a partial collection — missing icudtl.dat or the helper
# executable produces a silent white window or an instant crash.
# ---------------------------------------------------------------------------
datas = []
binaries = []
hiddenimports = [
    # Qt / PySide6 modules the app imports (directly or lazily).
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "PySide6.QtNetwork",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebChannel",
    "shiboken6",
    # Core deps
    "requests",
    "certifi",  # CA bundle — without it every HTTPS .anm resolution fails cert verification
    # Wallet backend (imported lazily by animica_internet.wallet)
    "animica",
]

# Bundle certifi's cacert.pem (its data file) so netcfg can point urllib/requests at it.
try:
    from PyInstaller.utils.hooks import collect_data_files
    datas += collect_data_files("certifi")
except Exception as exc:  # noqa: BLE001
    print(f"[spec] warning: collect_data_files('certifi') failed: {exc}")

try:
    from PyInstaller.utils.hooks import collect_all

    ps_datas, ps_binaries, ps_hidden = collect_all("PySide6")
    datas += ps_datas
    binaries += ps_binaries
    hiddenimports += ps_hidden
    print(
        f"[spec] collect_all('PySide6'): {len(ps_datas)} datas, "
        f"{len(ps_binaries)} binaries, {len(ps_hidden)} hidden imports"
    )
except Exception as exc:  # pragma: no cover - depends on PyInstaller version
    print(f"[spec] warning: collect_all('PySide6') failed: {exc}")
    # Fallback: at minimum grab QtWebEngine data + dynamic libs so the
    # official hooks have everything they need.
    try:
        from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs

        datas += collect_data_files("PySide6")
        binaries += collect_dynamic_libs("PySide6")
    except Exception as exc2:
        print(f"[spec] warning: PySide6 fallback collection failed: {exc2}")

# Qt plugins (platforms/, imageformats/, tls/, ...) — same as the proven
# miner-gui spec; harmless if collect_all already got them (deduped later).
try:
    from PyInstaller.utils.hooks.qt import collect_qt_plugins

    datas += collect_qt_plugins("PySide6")
except Exception as exc:  # pragma: no cover
    print(f"[spec] warning: collect_qt_plugins unavailable: {exc}")

# App assets (icons etc.), if present.
assets_dir = APP_DIR / "assets"
if assets_dir.exists():
    for asset in sorted(assets_dir.iterdir()):
        if asset.is_file():
            datas.append((str(asset), "assets"))

# Pull in the whole `animica` package tree (wallet backend, ml_dsa_65 signing)
# so lazy imports resolve offline in the frozen app. Best effort: the app must
# still build when the monorepo `animica` distribution is absent.
try:
    from PyInstaller.utils.hooks import collect_submodules

    hiddenimports += collect_submodules("animica")
except Exception as exc:  # pragma: no cover
    print(f"[spec] warning: collect_submodules('animica') failed: {exc}")

# De-duplicate while preserving order.
hiddenimports = list(dict.fromkeys(hiddenimports))

# ---------------------------------------------------------------------------
# Runtime hook: repair Qt plugin paths AND QtWebEngine helper/resource paths
# inside the frozen bundle (see qt_runtime_hook.py alongside this spec).
# ---------------------------------------------------------------------------
runtime_hooks = []
qt_hook = SPEC_DIR / "qt_runtime_hook.py"
if qt_hook.exists():
    runtime_hooks.append(str(qt_hook))
else:
    print(f"[spec] warning: qt_runtime_hook.py not found next to spec ({SPEC_DIR})")

a = Analysis(
    [str(ENTRY)],
    pathex=[str(APP_DIR), str(REPO_ROOT), str(REPO_ROOT / "python")],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=runtime_hooks,
    excludes=[
        "tkinter",
        "test",
        "tests",
        "pytest",
        # The .anm browser only needs animica's wallet/tx/crypto modules. collect_submodules
        # ("animica") also enumerates the AI/ENA/mining subtrees, which pull in torch/transformers
        # (hundreds of MB). Exclude them so the installer stays small and builds fast — none are
        # imported by the wallet path.
        "torch", "torchvision", "torchaudio", "triton",
        "transformers", "safetensors", "accelerate", "sentencepiece", "tokenizers",
        "sklearn", "scipy", "pandas", "matplotlib",
        "animica.ena", "animica.aicf", "animica.cli.ena", "animica.cli.aicf",
        "animica.cli.gui", "animica.cli.studio", "animica.cli.mining",
        "animica.hash_work", "animica.flagship_agent", "animica.agent_runtime",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# Platform icon, if one is present in assets/.
exe_icon = None
ico = APP_DIR / "assets" / "icon.ico"
icns = APP_DIR / "assets" / "icon.icns"
if IS_WINDOWS and ico.exists():
    exe_icon = str(ico)
elif IS_MACOS and icns.exists():
    exe_icon = str(icns)

# onedir layout: EXE has exclude_binaries=True and COLLECT gathers everything.
# onedir is MANDATORY for QtWebEngine (the Chromium helper must live on disk
# next to its resources; onefile extraction breaks sandbox/helper discovery).
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=USE_UPX,
    console=False,  # windowed app (no console)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=exe_icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=USE_UPX,
    upx_exclude=[
        # Never UPX Qt/Chromium binaries — corrupts them.
        "Qt*",
        "qt*",
        "QtWebEngineProcess*",
        "*.pak",
    ],
    name=APP_NAME,
)

# macOS: wrap the onedir COLLECT into an .app bundle.
if IS_MACOS:
    app = BUNDLE(
        coll,
        name=f"{APP_NAME}.app",
        icon=str(icns) if icns.exists() else None,
        bundle_identifier="org.animica.internet",
        version=APP_VERSION,
        info_plist={
            "CFBundleName": APP_NAME,
            "CFBundleDisplayName": "Animica Internet",
            "CFBundleShortVersionString": APP_VERSION,
            "CFBundleVersion": APP_VERSION,
            "NSHighResolutionCapable": True,
            "LSMinimumSystemVersion": "11.0",
            "NSRequiresAquaSystemAppearance": False,
            "CFBundlePackageType": "APPL",
            "LSApplicationCategoryType": "public.app-category.productivity",
            # QtWebEngine helper processes need these to load pages.
            "NSAppTransportSecurity": {"NSAllowsArbitraryLoads": True},
        },
    )
