// Build script for Animica Explorer (Tauri)
// - Embeds sane defaults for URL mode (compile-time constants)
// - Marks icons/config for rebuilds
// - Invokes tauri-build

use std::{env, fs, path::Path};

fn read_fallbacks_from_metadata(manifest_dir: &str) -> (Option<String>, Option<String>) {
    // Try to read ../config/app_metadata.json for `"site":{"remote": "...", "fallback_offline":"..."}`
    let meta_path = Path::new(manifest_dir).join("../config/app_metadata.json");
    let text = match fs::read_to_string(&meta_path) {
        Ok(s) => s,
        Err(_) => return (None, None),
    };
    // Extremely small/robust extract without adding build-deps:
    let remote = extract_json_string(&text, r#""remote""#);
    let fallback = extract_json_string(&text, r#""fallback_offline""#);
    (remote, fallback)
}

fn extract_json_string(haystack: &str, key: &str) -> Option<String> {
    // Finds key then the next quoted string value.
    let kpos = haystack.find(key)?;
    let after = &haystack[kpos..];
    let first_quote = after.find('"')?; // key opening
    let after_key = &after[first_quote + 1..];
    let colon = after_key.find(':')?;
    let after_colon = &after_key[colon + 1..];
    let start = after_colon.find('"')?;
    let rest = &after_colon[start + 1..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // Prefer explicit env, otherwise read from config, then hard-coded safe default.
    let (meta_remote, meta_fallback) = read_fallbacks_from_metadata(&manifest_dir);

    let default_url = env::var("EXPLORER_URL")
        .ok()
        .or(meta_remote)
        .unwrap_or_else(|| "https://explorer.animica.dev".to_string());

    let default_fallback = env::var("EXPLORER_URL_FALLBACK")
        .ok()
        .or(meta_fallback)
        .unwrap_or_else(|| "app://localhost/index.html".to_string());

    let allowed_hosts = env::var("EXPLORER_ALLOWED_HOSTS")
        .unwrap_or_else(|_| "explorer.animica.dev,rpc.animica.dev".to_string());

    // Expose as compile-time env (usable via option_env!("ANIMICA_*") or included file below).
    println!("cargo:rustc-env=ANIMICA_DEFAULT_URL={}", default_url);
    println!("cargo:rustc-env=ANIMICA_DEFAULT_FALLBACK_URL={}", default_fallback);
    println!("cargo:rustc-env=ANIMICA_ALLOWED_HOSTS={}", allowed_hosts);

    // Also emit a tiny generated module with constants (in case the app prefers include!()).
    let out_dir = env::var("OUT_DIR").unwrap();
    let built_path = Path::new(&out_dir).join("built_env.rs");
    let built = format!(
        r#"
// AUTO-GENERATED by build.rs — do not edit.
pub const DEFAULT_URL: &str = "{default_url}";
pub const DEFAULT_FALLBACK_URL: &str = "{default_fallback}";
pub const DEFAULT_ALLOWED_HOSTS: &str = "{allowed_hosts}";

// Optional icons as bytes (only if present in the repo). These can be used for
// tray icons or about dialogs at runtime if desired.
#[cfg(any())] // set to `cfg(feature = "embed-icons")` if you wire this up
pub const ICON_ICNS: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/icons/icon.icns"));
#[cfg(any())]
pub const ICON_ICO: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/icons/icon.ico"));
#[cfg(any())]
pub const ICON_128_PNG: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/icons/128x128.png"));
#[cfg(any())]
pub const ICON_256_PNG: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/icons/256x256.png"));
"#
    );
    fs::write(&built_path, built).expect("write built_env.rs");

    // Rebuild if env changes
    println!("cargo:rerun-if-env-changed=EXPLORER_URL");
    println!("cargo:rerun-if-env-changed=EXPLORER_URL_FALLBACK");
    println!("cargo:rerun-if-env-changed=EXPLORER_ALLOWED_HOSTS");

    // Rebuild if these files change
    let meta = Path::new(&manifest_dir).join("../config/app_metadata.json");
    if meta.exists() {
        println!("cargo:rerun-if-changed={}", meta.display());
    }

    for icon in [
        "icons/icon.icns",
        "icons/icon.ico",
        "icons/128x128.png",
        "icons/256x256.png",
        "tauri.conf.json",
    ] {
        let p = Path::new(&manifest_dir).join(icon);
        if p.exists() {
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }

    // Hand over to tauri-build for schema generation etc.
    tauri_build::build()
}
