/**
 * aicfChat — thin JSON-RPC wrapper for the chat-side AICF flow.
 *
 * Mirrors the python agent_runtime.aicf_client semantics:
 *   estimateCost → user signs payment → submit → stream → settle
 *
 * Endpoint defaults to whatever the user's connected wallet considers its
 * active node RPC. Override via VITE_AICF_RPC_URL at build time or by
 * passing rpcUrl into makeAicfChat().
 */

export type ChatJobSpec = {
  prompt: string;
  tierPreferred?: "tiny" | "small" | "flagship" | "large";
  maxOutputTokens?: number;
  temperature?: number;
  topP?: number;
  history?: Array<{ role: "user" | "assistant"; content: string }>;
  /**
   * Optional override for the Animica system framing prepended to every
   * turn. Defaults to ANIMICA_STUDIO_SYSTEM_PROMPT. Pass an empty string
   * to disable client-side framing (the worker still applies its own).
   */
  systemPrompt?: string;
};

/**
 * Animica context prepended to every prompt sent to a miner.
 *
 * Workers run small (0.5B–7B) off-the-shelf chat models that have zero
 * knowledge of Animica from pretraining, so without this header every
 * answer about the chain, tokenomics, mining, AICF, etc. is a
 * hallucination. The worker also injects its own short system prompt +
 * a RAG snippet, but we cannot rely on either being present (RAG index
 * may be missing; older miners predate the worker-side prompt), so we
 * ship the facts the model needs alongside the user turn.
 *
 * Keep this dense and factual — every token here is paid for by the
 * caller at quote time.
 */
const ANIMICA_STUDIO_SYSTEM_PROMPT = [
  "You are an assistant for Animica Studio (studio.animica.org), the official IDE for the Animica blockchain. This very reply is being generated by a real miner on the live Animica network and paid for in ANIMICA tokens by the user's connected wallet.",
  "",
  "Animica is a fully decentralized Layer-1 blockchain for verifiable AI and quantum-secure execution:",
  "- Native token: ANIMICA (denominated in 9-decimal nano-units on-chain).",
  "- Consensus: PoIES (Proof of Integrated External Services) — hash-share PoW combined with AI / quantum / storage proofs. Public Stratum pool at pool.animica.org:3333.",
  "- Post-quantum signatures: Dilithium3 (ML-DSA-65) for transactions and SPHINCS+ as a fallback.",
  "- Execution: deterministic Python-VM smart contracts with gas metering.",
  "- AICF (AI Compute Fund): protocol that lets miners earn ANIMICA per inference turn. Tiers: tiny (CPU), small (7B, single GPU), flagship (16B MoE — recommended), large (datacenter).",
  "- DA layer: namespaced data availability via an NMT (Namespaced Merkle Tree). RPC namespace is `da.*` (e.g. `da.status`, `da.listNamespaces`, `da.putBlob`).",
  "- RPC namespaces actually exposed by nodes: `state.*`, `chain.*`, `miner.*`, `tx.*`, `aicf.*`, `da.*`. There is no `animica.*` namespace — do not invent one.",
  "- Required tx fields when crafting raw transactions: kind, data, gasLimit, fee, nonce, chainId. Submit via tx.sendRawTransaction; debug failures via tx.explainReject and tx.debugVerifyRawTransaction.",
  "- Studio: a web IDE to edit → simulate → deploy → verify Python-VM contracts. The user pays per inference turn from the Animica browser extension wallet.",
  "",
  "Style: be concise (1–3 short paragraphs max unless explicitly asked for detail), use markdown when helpful, and stay code-focused. If asked something Animica-specific you genuinely do not know, say so plainly rather than inventing details.",
].join("\n");

export type ChatCostQuote = {
  costAnimica: number;
  latencyMs: number;
  tier: string;
  providers: number;
};

export type ChatJobSubmit = {
  jobId: string;
  acceptedTier: string;
  expectedProviderId: string;
  paymentTxHash: string;
};

export type ChatChunk = {
  text: string;
  isFinal: boolean;
  tokenCount?: number;
};

export type ChatSettlement = {
  jobId: string;
  text: string;
  actualCostAnimica: number;
  providerId: string;
  latencyMs: number;
};

let nextRpcId = 1;

/**
 * Compose the actual prompt string sent to the AICF worker. The worker
 * RPC accepts a single `prompt` field (no separate system / history
 * arrays), so we flatten the system header + prior turns + the new user
 * message here. Without this, follow-up questions like "and how does
 * its consensus work?" reach the model with zero indication of what
 * "its" refers to.
 *
 * History is capped at the last 10 turns to keep the prompt-token cost
 * (and hence per-turn ANM charge) bounded.
 */
function composeStudioPrompt(spec: ChatJobSpec): string {
  const sys = spec.systemPrompt ?? ANIMICA_STUDIO_SYSTEM_PROMPT;
  const parts: string[] = [];
  if (sys) {
    parts.push(sys);
    parts.push("");
  }
  const history = (spec.history ?? []).slice(-10);
  if (history.length > 0) {
    parts.push("=== conversation so far ===");
    for (const turn of history) {
      const role = turn.role === "user" ? "User" : "Assistant";
      parts.push(`${role}: ${turn.content}`);
    }
    parts.push("");
  }
  parts.push(`User: ${spec.prompt}`);
  parts.push("Assistant:");
  return parts.join("\n");
}

async function rpc<T>(url: string, method: string, params: unknown): Promise<T> {
  const r = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json", accept: "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", id: nextRpcId++, method, params }),
  });
  // Read the body as text first so we can detect HTML / nginx error pages
  // and surface a clear error instead of letting JSON.parse emit the
  // notorious `Unexpected token '<', "<html>..." is not valid JSON` which
  // tells the user nothing about what actually broke.
  const raw = await r.text();
  const ct = (r.headers.get("content-type") || "").toLowerCase();
  const looksHtml = !ct.includes("application/json") && /^\s*<(?:!doctype|html|head|body)/i.test(raw);
  if (!r.ok || looksHtml) {
    const snippet = raw.replace(/\s+/g, " ").trim().slice(0, 180);
    throw new Error(
      `AICF RPC ${method} non-JSON response (HTTP ${r.status}` +
      (ct ? `, ${ct}` : "") +
      `) from ${url}` +
      (snippet ? ` — ${snippet}` : "") +
      ". Check the RPC URL (should be https://mainnet.animica.org/rpc).",
    );
  }
  let body: { error?: { code: number | string; message: string; data?: unknown }; result?: T };
  try {
    body = JSON.parse(raw);
  } catch (parseErr) {
    const snippet = raw.replace(/\s+/g, " ").trim().slice(0, 180);
    throw new Error(
      `AICF RPC ${method} returned malformed JSON from ${url}` +
      (snippet ? ` — ${snippet}` : "") +
      ` (${parseErr instanceof Error ? parseErr.message : String(parseErr)})`,
    );
  }
  if (body.error) {
    const err = new Error(`AICF ${body.error.code}: ${body.error.message}`);
    (err as Error & { data?: unknown }).data = body.error.data;
    throw err;
  }
  return body.result as T;
}

export type AicfChatClient = ReturnType<typeof makeAicfChat>;

export function makeAicfChat(rpcUrl: string) {
  if (!rpcUrl) throw new Error("aicfChat: rpcUrl required");

  return {
    estimateCost: (spec: ChatJobSpec) => {
      const composed = composeStudioPrompt(spec);
      return rpc<ChatCostQuote>(rpcUrl, "aicf.estimateJobCost", {
        prompt_tokens: Math.max(1, Math.floor(composed.length / 4)),
        max_output_tokens: spec.maxOutputTokens ?? 1024,
        tier_preferred: spec.tierPreferred,
        job_kind: "AI",
      }).then((raw) => ({
        costAnimica: Number((raw as { cost_animica?: number }).cost_animica ?? 0),
        latencyMs: Number((raw as { latency_ms?: number }).latency_ms ?? 0),
        tier: String((raw as { tier?: string }).tier ?? spec.tierPreferred ?? "small"),
        providers: Number((raw as { providers?: number }).providers ?? 0),
      }));
    },

    submit: (spec: ChatJobSpec, paymentTxHash: string) =>
      rpc<{
        job_id: string;
        accepted_tier: string;
        provider_id: string;
      }>(rpcUrl, "aicf.submitInferenceJob", {
        spec: {
          prompt: composeStudioPrompt(spec),
          tier_preferred: spec.tierPreferred,
          job_kind: "AI",
          max_output_tokens: spec.maxOutputTokens ?? 1024,
          temperature: spec.temperature ?? 0.2,
          top_p: spec.topP ?? 0.95,
          metadata: { history_len: spec.history?.length ?? 0 },
        },
        payment: { txn_hash: paymentTxHash },
      }).then((raw) => ({
        jobId: raw.job_id,
        acceptedTier: raw.accepted_tier,
        expectedProviderId: raw.provider_id,
        paymentTxHash,
      })),

    streamOnce: (jobId: string, cursor: number) =>
      rpc<{
        text: string;
        final: boolean;
        next_cursor?: number;
        token_count?: number;
      }>(rpcUrl, "aicf.streamJob", { job_id: jobId, cursor }).then((raw) => ({
        text: raw.text ?? "",
        isFinal: !!raw.final,
        nextCursor: raw.next_cursor ?? cursor + (raw.text?.length ?? 0),
        tokenCount: raw.token_count,
      })),

    settle: (jobId: string) =>
      rpc<{
        text: string;
        cost_animica: number;
        provider_id: string;
        latency_ms: number;
      }>(rpcUrl, "aicf.settleJob", { job_id: jobId }).then((raw) => ({
        jobId,
        text: raw.text ?? "",
        actualCostAnimica: Number(raw.cost_animica ?? 0),
        providerId: raw.provider_id ?? "",
        latencyMs: Number(raw.latency_ms ?? 0),
      })),

    /**
     * Convenience: run a full turn end-to-end. Caller supplies a payer
     * function that takes (cost, recipient) and returns the txn hash.
     */
    runTurn: async (
      spec: ChatJobSpec,
      pay: (costAnimica: number, recipient: string) => Promise<string>,
      onChunk?: (c: ChatChunk) => void,
      treasuryAddress = "aicf-treasury",
      pollIntervalMs = 250,
      timeoutMs = 60_000,
    ): Promise<ChatSettlement> => {
      const composed = composeStudioPrompt(spec);
      const quote = await rpc<{
        cost_animica?: number;
        latency_ms?: number;
        tier?: string;
        providers?: number;
      }>(rpcUrl, "aicf.estimateJobCost", {
        prompt_tokens: Math.max(1, Math.floor(composed.length / 4)),
        max_output_tokens: spec.maxOutputTokens ?? 1024,
        tier_preferred: spec.tierPreferred,
        job_kind: "AI",
      });
      const cost = Number(quote.cost_animica ?? 0);
      const txHash = await pay(cost, treasuryAddress);
      const submitted = await rpc<{
        job_id: string;
        accepted_tier: string;
        provider_id: string;
      }>(rpcUrl, "aicf.submitInferenceJob", {
        spec: {
          prompt: composed,
          tier_preferred: spec.tierPreferred,
          job_kind: "AI",
          max_output_tokens: spec.maxOutputTokens ?? 1024,
          temperature: spec.temperature ?? 0.2,
          top_p: spec.topP ?? 0.95,
          metadata: { history_len: spec.history?.length ?? 0 },
        },
        payment: { txn_hash: txHash },
      });
      let cursor = 0;
      const deadline = Date.now() + timeoutMs;
      while (Date.now() < deadline) {
        const chunk = await rpc<{
          text: string;
          final: boolean;
          next_cursor?: number;
        }>(rpcUrl, "aicf.streamJob", { job_id: submitted.job_id, cursor });
        if (chunk.text) onChunk?.({ text: chunk.text, isFinal: false });
        cursor = chunk.next_cursor ?? cursor + (chunk.text?.length ?? 0);
        if (chunk.final) break;
        await new Promise((r) => setTimeout(r, pollIntervalMs));
      }
      const settle = await rpc<{
        text: string;
        cost_animica: number;
        provider_id: string;
        latency_ms: number;
      }>(rpcUrl, "aicf.settleJob", { job_id: submitted.job_id });
      onChunk?.({ text: "", isFinal: true });
      return {
        jobId: submitted.job_id,
        text: settle.text ?? "",
        actualCostAnimica: Number(settle.cost_animica ?? 0),
        providerId: settle.provider_id ?? "",
        latencyMs: Number(settle.latency_ms ?? 0),
      };
    },
  };
}
