/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BANMBridgeControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BURNER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MINTER_ROLE"
      | "OPERATOR_ROLE"
      | "PAUSER_ROLE"
      | "VAULT_MANAGER_ROLE"
      | "burnExecutedForOrder"
      | "capDay"
      | "chainConfigs"
      | "configureChain"
      | "dailyMintCap"
      | "dailyReleaseCap"
      | "executeMint"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "markReleaseCompleted"
      | "markReleaseRequested"
      | "mintExecutedForOrder"
      | "mintedToday"
      | "pause"
      | "paused"
      | "registerBurn"
      | "rejectMint"
      | "releaseCompletedForOrder"
      | "releasedToday"
      | "renounceRole"
      | "revokeRole"
      | "setCaps"
      | "supportsInterface"
      | "token"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BurnExecuted"
      | "BurnRequested"
      | "CapsUpdated"
      | "ChainConfigured"
      | "MintExecuted"
      | "MintRejected"
      | "MintRequested"
      | "Paused"
      | "ReleaseCompleted"
      | "ReleaseRequested"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BURNER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULT_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "burnExecutedForOrder",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "capDay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "chainConfigs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "configureChain",
    values: [BigNumberish, boolean, AddressLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyMintCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyReleaseCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeMint",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markReleaseCompleted",
    values: [BytesLike, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "markReleaseRequested",
    values: [BytesLike, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintExecutedForOrder",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintedToday",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerBurn",
    values: [BytesLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectMint",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseCompletedForOrder",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releasedToday",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCaps",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BURNER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULT_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnExecutedForOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "capDay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyMintCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyReleaseCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markReleaseCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markReleaseRequested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintExecutedForOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintedToday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseCompletedForOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasedToday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCaps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace BurnExecutedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    from: AddressLike,
    amount: BigNumberish,
    externalRef: string
  ];
  export type OutputTuple = [
    orderId: string,
    from: string,
    amount: bigint,
    externalRef: string
  ];
  export interface OutputObject {
    orderId: string;
    from: string;
    amount: bigint;
    externalRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BurnRequestedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    from: AddressLike,
    amount: BigNumberish,
    externalRef: string
  ];
  export type OutputTuple = [
    orderId: string,
    from: string,
    amount: bigint,
    externalRef: string
  ];
  export interface OutputObject {
    orderId: string;
    from: string;
    amount: bigint;
    externalRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapsUpdatedEvent {
  export type InputTuple = [
    dailyMintCap: BigNumberish,
    dailyReleaseCap: BigNumberish
  ];
  export type OutputTuple = [dailyMintCap: bigint, dailyReleaseCap: bigint];
  export interface OutputObject {
    dailyMintCap: bigint;
    dailyReleaseCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainConfiguredEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    enabled: boolean,
    router: AddressLike,
    vault: AddressLike,
    label: string
  ];
  export type OutputTuple = [
    chainId: bigint,
    enabled: boolean,
    router: string,
    vault: string,
    label: string
  ];
  export interface OutputObject {
    chainId: bigint;
    enabled: boolean;
    router: string;
    vault: string;
    label: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintExecutedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    to: AddressLike,
    amount: BigNumberish,
    feeAmount: BigNumberish,
    externalRef: string
  ];
  export type OutputTuple = [
    orderId: string,
    to: string,
    amount: bigint,
    feeAmount: bigint,
    externalRef: string
  ];
  export interface OutputObject {
    orderId: string;
    to: string;
    amount: bigint;
    feeAmount: bigint;
    externalRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintRejectedEvent {
  export type InputTuple = [orderId: BytesLike, reason: string];
  export type OutputTuple = [orderId: string, reason: string];
  export interface OutputObject {
    orderId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintRequestedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    to: AddressLike,
    amount: BigNumberish,
    feeAmount: BigNumberish,
    externalRef: string
  ];
  export type OutputTuple = [
    orderId: string,
    to: string,
    amount: bigint,
    feeAmount: bigint,
    externalRef: string
  ];
  export interface OutputObject {
    orderId: string;
    to: string;
    amount: bigint;
    feeAmount: bigint;
    externalRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseCompletedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    animicaAddress: string,
    amount: BigNumberish,
    animicaTxHash: string
  ];
  export type OutputTuple = [
    orderId: string,
    animicaAddress: string,
    amount: bigint,
    animicaTxHash: string
  ];
  export interface OutputObject {
    orderId: string;
    animicaAddress: string;
    amount: bigint;
    animicaTxHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseRequestedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    animicaAddress: string,
    amount: BigNumberish,
    externalRef: string
  ];
  export type OutputTuple = [
    orderId: string,
    animicaAddress: string,
    amount: bigint,
    externalRef: string
  ];
  export interface OutputObject {
    orderId: string;
    animicaAddress: string;
    amount: bigint;
    externalRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BANMBridgeController extends BaseContract {
  connect(runner?: ContractRunner | null): BANMBridgeController;
  waitForDeployment(): Promise<this>;

  interface: BANMBridgeControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BURNER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MINTER_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  VAULT_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  burnExecutedForOrder: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  capDay: TypedContractMethod<[], [bigint], "view">;

  chainConfigs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, string, string, string] & {
        enabled: boolean;
        router: string;
        vault: string;
        label: string;
      }
    ],
    "view"
  >;

  configureChain: TypedContractMethod<
    [
      chainId: BigNumberish,
      enabled: boolean,
      router: AddressLike,
      vault: AddressLike,
      label: string
    ],
    [void],
    "nonpayable"
  >;

  dailyMintCap: TypedContractMethod<[], [bigint], "view">;

  dailyReleaseCap: TypedContractMethod<[], [bigint], "view">;

  executeMint: TypedContractMethod<
    [
      orderId: BytesLike,
      to: AddressLike,
      amount: BigNumberish,
      feeAmount: BigNumberish,
      externalRef: string
    ],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  markReleaseCompleted: TypedContractMethod<
    [
      orderId: BytesLike,
      animicaAddress: string,
      amount: BigNumberish,
      animicaTxHash: string
    ],
    [void],
    "nonpayable"
  >;

  markReleaseRequested: TypedContractMethod<
    [
      orderId: BytesLike,
      animicaAddress: string,
      amount: BigNumberish,
      externalRef: string
    ],
    [void],
    "nonpayable"
  >;

  mintExecutedForOrder: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  mintedToday: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerBurn: TypedContractMethod<
    [
      orderId: BytesLike,
      from: AddressLike,
      amount: BigNumberish,
      externalRef: string
    ],
    [void],
    "nonpayable"
  >;

  rejectMint: TypedContractMethod<
    [orderId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  releaseCompletedForOrder: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  releasedToday: TypedContractMethod<[], [bigint], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setCaps: TypedContractMethod<
    [dailyMintCap_: BigNumberish, dailyReleaseCap_: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  token: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BURNER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MINTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VAULT_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "burnExecutedForOrder"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "capDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "chainConfigs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, string, string, string] & {
        enabled: boolean;
        router: string;
        vault: string;
        label: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "configureChain"
  ): TypedContractMethod<
    [
      chainId: BigNumberish,
      enabled: boolean,
      router: AddressLike,
      vault: AddressLike,
      label: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dailyMintCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyReleaseCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeMint"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      to: AddressLike,
      amount: BigNumberish,
      feeAmount: BigNumberish,
      externalRef: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "markReleaseCompleted"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      animicaAddress: string,
      amount: BigNumberish,
      animicaTxHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markReleaseRequested"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      animicaAddress: string,
      amount: BigNumberish,
      externalRef: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintExecutedForOrder"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintedToday"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerBurn"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      from: AddressLike,
      amount: BigNumberish,
      externalRef: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectMint"
  ): TypedContractMethod<
    [orderId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseCompletedForOrder"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "releasedToday"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCaps"
  ): TypedContractMethod<
    [dailyMintCap_: BigNumberish, dailyReleaseCap_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BurnExecuted"
  ): TypedContractEvent<
    BurnExecutedEvent.InputTuple,
    BurnExecutedEvent.OutputTuple,
    BurnExecutedEvent.OutputObject
  >;
  getEvent(
    key: "BurnRequested"
  ): TypedContractEvent<
    BurnRequestedEvent.InputTuple,
    BurnRequestedEvent.OutputTuple,
    BurnRequestedEvent.OutputObject
  >;
  getEvent(
    key: "CapsUpdated"
  ): TypedContractEvent<
    CapsUpdatedEvent.InputTuple,
    CapsUpdatedEvent.OutputTuple,
    CapsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ChainConfigured"
  ): TypedContractEvent<
    ChainConfiguredEvent.InputTuple,
    ChainConfiguredEvent.OutputTuple,
    ChainConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "MintExecuted"
  ): TypedContractEvent<
    MintExecutedEvent.InputTuple,
    MintExecutedEvent.OutputTuple,
    MintExecutedEvent.OutputObject
  >;
  getEvent(
    key: "MintRejected"
  ): TypedContractEvent<
    MintRejectedEvent.InputTuple,
    MintRejectedEvent.OutputTuple,
    MintRejectedEvent.OutputObject
  >;
  getEvent(
    key: "MintRequested"
  ): TypedContractEvent<
    MintRequestedEvent.InputTuple,
    MintRequestedEvent.OutputTuple,
    MintRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReleaseCompleted"
  ): TypedContractEvent<
    ReleaseCompletedEvent.InputTuple,
    ReleaseCompletedEvent.OutputTuple,
    ReleaseCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ReleaseRequested"
  ): TypedContractEvent<
    ReleaseRequestedEvent.InputTuple,
    ReleaseRequestedEvent.OutputTuple,
    ReleaseRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BurnExecuted(bytes32,address,uint256,string)": TypedContractEvent<
      BurnExecutedEvent.InputTuple,
      BurnExecutedEvent.OutputTuple,
      BurnExecutedEvent.OutputObject
    >;
    BurnExecuted: TypedContractEvent<
      BurnExecutedEvent.InputTuple,
      BurnExecutedEvent.OutputTuple,
      BurnExecutedEvent.OutputObject
    >;

    "BurnRequested(bytes32,address,uint256,string)": TypedContractEvent<
      BurnRequestedEvent.InputTuple,
      BurnRequestedEvent.OutputTuple,
      BurnRequestedEvent.OutputObject
    >;
    BurnRequested: TypedContractEvent<
      BurnRequestedEvent.InputTuple,
      BurnRequestedEvent.OutputTuple,
      BurnRequestedEvent.OutputObject
    >;

    "CapsUpdated(uint256,uint256)": TypedContractEvent<
      CapsUpdatedEvent.InputTuple,
      CapsUpdatedEvent.OutputTuple,
      CapsUpdatedEvent.OutputObject
    >;
    CapsUpdated: TypedContractEvent<
      CapsUpdatedEvent.InputTuple,
      CapsUpdatedEvent.OutputTuple,
      CapsUpdatedEvent.OutputObject
    >;

    "ChainConfigured(uint256,bool,address,address,string)": TypedContractEvent<
      ChainConfiguredEvent.InputTuple,
      ChainConfiguredEvent.OutputTuple,
      ChainConfiguredEvent.OutputObject
    >;
    ChainConfigured: TypedContractEvent<
      ChainConfiguredEvent.InputTuple,
      ChainConfiguredEvent.OutputTuple,
      ChainConfiguredEvent.OutputObject
    >;

    "MintExecuted(bytes32,address,uint256,uint256,string)": TypedContractEvent<
      MintExecutedEvent.InputTuple,
      MintExecutedEvent.OutputTuple,
      MintExecutedEvent.OutputObject
    >;
    MintExecuted: TypedContractEvent<
      MintExecutedEvent.InputTuple,
      MintExecutedEvent.OutputTuple,
      MintExecutedEvent.OutputObject
    >;

    "MintRejected(bytes32,string)": TypedContractEvent<
      MintRejectedEvent.InputTuple,
      MintRejectedEvent.OutputTuple,
      MintRejectedEvent.OutputObject
    >;
    MintRejected: TypedContractEvent<
      MintRejectedEvent.InputTuple,
      MintRejectedEvent.OutputTuple,
      MintRejectedEvent.OutputObject
    >;

    "MintRequested(bytes32,address,uint256,uint256,string)": TypedContractEvent<
      MintRequestedEvent.InputTuple,
      MintRequestedEvent.OutputTuple,
      MintRequestedEvent.OutputObject
    >;
    MintRequested: TypedContractEvent<
      MintRequestedEvent.InputTuple,
      MintRequestedEvent.OutputTuple,
      MintRequestedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReleaseCompleted(bytes32,string,uint256,string)": TypedContractEvent<
      ReleaseCompletedEvent.InputTuple,
      ReleaseCompletedEvent.OutputTuple,
      ReleaseCompletedEvent.OutputObject
    >;
    ReleaseCompleted: TypedContractEvent<
      ReleaseCompletedEvent.InputTuple,
      ReleaseCompletedEvent.OutputTuple,
      ReleaseCompletedEvent.OutputObject
    >;

    "ReleaseRequested(bytes32,string,uint256,string)": TypedContractEvent<
      ReleaseRequestedEvent.InputTuple,
      ReleaseRequestedEvent.OutputTuple,
      ReleaseRequestedEvent.OutputObject
    >;
    ReleaseRequested: TypedContractEvent<
      ReleaseRequestedEvent.InputTuple,
      ReleaseRequestedEvent.OutputTuple,
      ReleaseRequestedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
